apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: z6aa2o2ia-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: z6aa2o2ia-nodejs 
  name: z6aa2o2ia-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: z6aa2o2ia-nodejs 
